version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/isyll/go-api-starter

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
